<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hot Leads and Document Collection</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .container {
            max-width: 900px;
            margin: 50px auto;
            margin-top: 8%;
        }

        div#sidebar-menu {
            position: fixed;
        }

        .table .thead-dark th {
            color: #fff;
            background-color: #000000;
            border-color: #454d55;
        }

        .lead-status {
            max-width: 150px;
        }

        .action-column {
            width: 180px;
        }

        /* Adjust width of the select element */
        .action-column select {
            width: 130px;
        }

        @media (max-width: 768px) {
            .container {
                margin-top: 20px;
            }

            .container table {
                font-size: 14px;
            }

            .container th,
            .container td {
                padding: 8px;
            }

            .container .action-column {
                width: 150px;
            }

            .container .action-column select {
                width: 110px;
            }
        }
    </style>
</head>

<body>
    <?php
    session_start(); // Start the session
    include 'leftsidesales.php'; // Include left sidebar
    include 'config.php'; // Include database configuration

    $loggedInUser = isset($_SESSION['username']) ? $_SESSION['username'] : null;
    ?>

    <div class="container" style="margin-left:90px">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Welcome !</h4>
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="dashboardsales.php">Dashboard</a></li>
                            <li class="breadcrumb-item active">Hot Leads!</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        
        <h1 class="mb-4">Hot Leads and Document Collection</h1>
        
        <!-- Search Bar -->
        <div class="form-group">
            <input type="text" id="searchInput" class="form-control" placeholder="Search by Name or ID">
        </div>
        
        <!-- Table -->
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>Full Name</th>
                        <th>Email</th>
                        <th>Phone Number</th>
                        <th>Lead Status</th>
                        <th>Lead Generated by/ Assigned To</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody id="leadsTableBody">
                    <?php

                    if ($loggedInUser) {
                        $assignedSalesperson = $loggedInUser;

                        $sql = "SELECT ID, FullName, Email, PhoneNumber, generatedby 
                                FROM personalinformation 
                                WHERE (assignedto = '$assignedSalesperson' 
                                OR generatedby = 'Self(" . $loggedInUser . ")') 
                                AND LeadStatus='Hot Lead'";
                        $result = $conn->query($sql);

                        if ($result->num_rows > 0) {
                            while ($row = $result->fetch_assoc()) {
                                echo "<tr>";
                                echo "<td>" . $row["ID"] . "</td>";
                                echo "<td>" . $row["FullName"] . "</td>";
                                echo "<td>" . $row["Email"] . "</td>";
                                echo "<td>" . $row["PhoneNumber"] . "</td>";
                                echo "<td>Hot Lead</td>";
                                echo "<td>" . $row["generatedby"] . "</td>";
                                echo '<td><a href="viewdocumentssales.php?id=' . $row["ID"] . '" class="btn btn-primary btn-sm">View and Upload Documents</a></td>';
                                echo "</tr>";
                            }
                        } else {
                            echo "<tr><td colspan='6'>No hot leads found</td></tr>";
                        }
                    } else {
                        echo "<tr><td colspan='6'>You are not authorized to view this data</td></tr>";
                    }

                    $conn->close();
                    ?>
                </tbody>
            </table>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#searchInput').on('input', function () {
                var query = $(this).val();
                $.ajax({
                    url: 'search_hot_leads_sales.php',
                    method: 'POST',
                    data: { query: query },
                    success: function (data) {
                        $('#leadsTableBody').html(data);
                    }
                });
            });
        });
    </script>
</body>

</html>
