<?php
session_start();
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leads Management</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .container {
            max-width: 900px;
            margin: 50px auto;
            margin-top: 8%;
        }

        div#sidebar-menu {
            position: fixed;
        }

        .table .thead-dark th {
            color: #fff;
            background-color: #000000;
            border-color: #454d55;
        }

        .lead-status {
            max-width: 150px;
        }

        .action-column {
            width: 180px;
        }

        .action-column select {
            width: 130px;
        }

        .count-chip {
            background-color: #007bff;
            color: #fff;
            border-radius: 20px;
            padding: 8px 12px;
            margin-right: 10px;
        }
    </style>
</head>

<body>
    <?php include 'leftside.php'; ?>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Welcome !</h4>
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="dashboard.php">Dashboard</a></li>
                            <li class="breadcrumb-item active">Welcome !</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <h1 class="mb-4">Leads Management</h1>
        <!-- Counting chips -->
        <div class="mb-3">
            <?php
            include 'config.php';

            // Count Total Leads
            $totalLeadsQuery = "SELECT COUNT(*) as total_leads FROM personalinformation";
            $totalLeadsResult = $conn->query($totalLeadsQuery);
            $totalLeadsCount = $totalLeadsResult->fetch_assoc()['total_leads'];

            // Count Gold Loan Leads
            $goldLoanQuery = "SELECT COUNT(*) as gold_loan_leads FROM personalinformation WHERE LoanPurpose = 'Gold Loan'";
            $goldLoanResult = $conn->query($goldLoanQuery);
            $goldLoanCount = $goldLoanResult->fetch_assoc()['gold_loan_leads'];

            // Count Home Loan Leads
            $homeLoanQuery = "SELECT COUNT(*) as home_loan_leads FROM personalinformation WHERE LoanPurpose = 'Home Loan'";
            $homeLoanResult = $conn->query($homeLoanQuery);
            $homeLoanCount = $homeLoanResult->fetch_assoc()['home_loan_leads'];

            // Count LAP (Loan Against Property) Leads
            $lapQuery = "SELECT COUNT(*) as lap_leads FROM personalinformation WHERE LoanPurpose = 'LAP'";
            $lapResult = $conn->query($lapQuery);
            $lapCount = $lapResult->fetch_assoc()['lap_leads'];
            
            $personalQuery = "SELECT COUNT(*) as personal_leads FROM personalinformation WHERE LoanPurpose = 'Personal Loan'";
            $personalResult = $conn->query($personalQuery);
            $personalCount = $personalResult->fetch_assoc()['personal_leads'];

            // Display counting chips
            echo "<span class='count-chip'>Total Leads: " . $totalLeadsCount . "</span>";
            echo "<span class='count-chip'>Personal Loan: " . $personalCount . "</span>";
            echo "<span class='count-chip'>Gold Loan: " . $goldLoanCount . "</span>";
            echo "<span class='count-chip'>Home Loan: " . $homeLoanCount . "</span>";
            echo "<span class='count-chip'>Loan Against Property (LAP): " . $lapCount . "</span>";

            $conn->close();
            ?>
        </div>
        <!-- Search bar -->
        <div class="row mb-3">
            <div class="col-12">
                <input type="text" id="search-input" class="form-control"
                    placeholder="Search by Name, Lead ID, Phone Number, or Loan Purpose">
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>Full Name</th>
                        <th>Email</th>
                        <th>Phone Number</th>
                        <th>Occupation</th>
                        <th>Employer</th>
                        <th>Loan Amount</th>
                        <th>Loan Purpose</th>
                        <th>Generated by</th>
                        <th>Assigned to</th>
                        <th>Lead Status</th>
                        <th class="action-column">Action</th>
                        <th class="action-column">Assign to</th>
                    </tr>
                </thead>
                <tbody id="leads-table-body">
                    <?php
                    include 'config.php';

                    $sql = "SELECT * FROM personalinformation";
                    $result = $conn->query($sql);

                    if ($result->num_rows > 0) {
                        while ($row = $result->fetch_assoc()) {
                            echo "<tr>";
                            echo "<td>" . $row["ID"] . "</td>";
                            echo "<td>" . $row["FullName"] . "</td>";
                            echo "<td>" . $row["Email"] . "</td>";
                            echo "<td>" . $row["PhoneNumber"] . "</td>";
                            echo "<td>" . $row["details1"] . "</td>";
                            echo "<td>" . $row["employer1"] . "</td>";
                            echo "<td>" . $row["LoanAmount"] . "</td>";
                            echo "<td>" . $row["LoanPurpose"] . "</td>";
                            echo "<td>" . $row["generatedby"] . "</td>";
                            echo "<td>" . $row["assignedto"] . "</td>";
                            echo "<td>" . $row["LeadStatus"] . "</td>";
                            echo '<td><form action="update_lead.php" method="POST" class="lead-status">
                                    <input type="hidden" name="leadID" value="' . $row["ID"] . '">
                                    <div class="form-group">
                                        <select class="form-control" name="leadStatus">
                                            <option value="Hot Lead">Hot Lead</option>
                                            <option value="Cold Lead">Cold Lead</option>
                                            <option value="Rejection">Rejection</option>
                                            <option value="New Lead">New Lead</option>
                                        </select>
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-sm">Update</button>
                                </form></td>';
                            echo '<td><form action="assign_lead.php" method="POST" class="assign-lead">
                                    <input type="hidden" name="leadID" value="' . $row["ID"] . '">
                                    <div class="form-group">
                                        <select class="form-control" name="assignedTo">';
                            
                            // Fetch users with role 'branchmanager' or 'sales'
                            $usersSql = "SELECT username FROM users WHERE role IN ('branchmanager', 'sales')";
                            $usersResult = $conn->query($usersSql);
                            if ($usersResult->num_rows > 0) {
                                while ($userRow = $usersResult->fetch_assoc()) {
                                    echo "<option value='" . $userRow['username'] . "'>" . $userRow['username'] . "</option>";
                                }
                            }

                            echo '                    </select>
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-sm">Assign</button>
                                </form></td>';
                            echo "</tr>";
                        }
                    } else {
                        echo "<tr><td colspan='13'>No leads found</td></tr>";
                    }

                    $conn->close();
                    ?>
                </tbody>
            </table>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#search-input').on('input', function() {
                let query = $(this).val();
                $.ajax({
                    url: 'search_leads.php',
                    method: 'GET',
                    data: { query: query },
                    success: function(data) {
                        $('#leads-table-body').html(data);
                    }
                });
            });
        });
    </script>
</body>

</html>
