<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pending Leads Details</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        h1 {
            text-align: center;
            margin-top: 20px;
            color: #1C84EE;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background-color: #fff;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        th, td {
            padding: 12px;
            border: 1px solid #ddd;
            text-align: left;
            color: #333;
        }
        th {
            background-color: #1C84EE;
            color: #fff;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Pending Leads Details</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Sno</th>
                <th>Date</th>
                <th>Case Of</th>
                <th>Full Name</th>
                <th>Email</th>
                <th>Mobile Number</th>
                <th>Aadhar App.</th>
                <th>PAN App.</th>
                <th>Aadhar CO-App</th>
                <th>Pan CO-App</th>
                <th>Scoring Agency App.</th>
                <th>CS App</th>
                <th>Scoring Agency CO-App.</th>
                <th>CS Co-App</th>
                <th>Co-App Name</th>
                <th>App. Occupation</th>
                <th>App. Employer</th>
                <th>Co-App Work</th>
                <th>App. Income</th>
                <th>Income Mode</th>
                <th>CO-App. Income</th>
                <th>App. Residency</th>
                <th>CO-App. Residency</th>
                <th>Relation with CO-App.</th>
                <th>Reason for Loan</th>
                <th>Name 1</th>
                <th>Relation 1</th>
                <th>Contact 1</th>
                <th>Name 2</th>
                <th>Relation 2</th>
                <th>Contact 2</th>
                <th>Name 3</th>
                <th>Relation 3</th>
                <th>Contact 3</th>
                <th>Name 4</th>
                <th>Relation 4</th>
                <th>Contact 4</th>
                <th>Name 5</th>
                <th>Relation 5</th>
                <th>Contact 5</th>
                <th>Name 6</th>
                <th>Relation 6</th>
                <th>Contact 6</th>
                <th>Name 7</th>
                <th>Relation 7</th>
                <th>Contact 7</th>
                <th>Name 8</th>
                <th>Relation 8</th>
                <th>Contact 8</th>
                <th>Name 9</th>
                <th>Relation 9</th>
                <th>Contact 9</th>
                <th>Name 10</th>
                <th>Relation 10</th>
                <th>Contact 10</th>
                <th>Bank Account No</th>
                <th>Monthly Income</th>
                <th>IFSC</th>
                <th>Bank Name</th>
                <th>Loan Amount</th>
                <th>Loan Purpose</th>
                <th>Address</th>
                <th>Lead Status</th>
                <th>Is Hot Lead</th>
                <th>Generated By</th>
                <th>Assigned To</th>
                <th>Remarks</th>
                <th>Step Reached</th>
                <th>Loan Status</th>
            </tr>
        </thead>
        <tbody>
            <?php
            include 'config.php';

            // Fetch all columns from the personalinformation table
            $query_all_details = "SELECT * FROM personalinformation WHERE LeadStatus = 'New Lead' ";
            $result_all_details = mysqli_query($conn, $query_all_details);

            // Check if query execution was successful
            if ($result_all_details) {
                // Fetch all rows from the result set
                $all_details_data = mysqli_fetch_all($result_all_details, MYSQLI_ASSOC);
                foreach ($all_details_data as $row): ?>
            <tr>
                <?php foreach ($row as $value): ?>
                <td><?php echo $value; ?></td>
                <?php endforeach; ?>
            </tr>
            <?php endforeach;
            } else {
                // Handle error if query execution failed
                echo "<tr><td colspan='50'>No data found.</td></tr>";
            }

            // Close the database connection
            mysqli_close($conn);
            ?>
        </tbody>
    </table>
</body>
</html>
